inherit_gem:
  prettier: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/**/*
    - lib/tasks/cucumber.rake
  TargetRubyVersion: 3.2

Layout/LineLength:
  Exclude:
    - "test/**/*"
    - "features/**/*"

# Blocks are used to structure tests and are part of the shoulda dsl.
# The standard BlockLength limits are too stringent for this purpose.
# Block DSL is also used in routes
# We should be careful keeping rake tasks here, as large tasks are still an issue.
# Not sure if we need to split namespaces across several files though.
# We exclude builders, as they are concerned with rendering xml
Metrics/BlockLength:
  Exclude:
    - Gemfile
    - "db/seeds/**/*"
    - "**/*.builder"
    - "db/schema.rb"
    - "test/**/*"
    - config/routes.rb
  CountAsOne:
    - array
    - hash
    - heredoc

# Method length limits make little sense when you are describing a table schema
# or a view.
Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ClassLength:
  Exclude:
    - "test/**/*"
  CountAsOne:
    - array
    - hash
    - heredoc

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

# Turns numbers like 1234567 into 1_234_567. However this code deals with large
# numbers for things like barcodes which we don't want displayed like that.
Style/NumericLiterals:
  Enabled: false

Style/WordArray:
  MinSize: 3

Lint/Debugger:
  Exclude:
    - "features/step_definitions/authentication_steps.rb"
    - "features/step_definitions/web_steps.rb"
