mysql: &MYSQL
  adapter: mysql2
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *MYSQL
  database: process_tracking_development

test: &test
  <<: *MYSQL
  database: process_tracking_test

cucumber:
  <<: *test
