mysql: &MYSQL
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  port: 3306

development:
  <<: *MYSQL
  database: process_tracking_development

test: &test
  <<: *MYSQL
  database: process_tracking_test

cucumber:
  <<: *test
