# Triggered on dispatching the action
# Create a release and build

name: Asset - on dispatch; build release and publish
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: Release/Asset name
        required: true
        default: x.y.z-uat.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Compile Build
        run: ./compile-build

      - name: Create release and upload release.tar.gz
        uses: ncipollo/release-action@v1.8.8
        with:
          name: ${{ github.event.inputs.release_name }}
          tag: v${{ github.event.inputs.release_name }}
          prerelease: true
          commit: ${{ github.sha }}
          artifacts: release.tar.gz
          artifactErrorsFailBuild: true
