name: Ruby Lint and Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
    # Services
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices
    services:
      mysql:
        # Use the Mysql docker image https://hub.docker.com/_/mysql
        image: mysql:8.0
        ports:
          - 3306:3306 # Default port mappings
          # Monitor the health of the container to mesaure when it is ready
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: "" # Set root PW to nothing
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache:
            true # Runs bundle install and caches gems. See the ruby_test.yml
            # example if you need more control over bundler.
      - name: Run rubocop
        run: bundle exec rubocop --extra-details --display-style-guide --parallel
      - name: Run prettier
        run: bundle exec rbprettier --check . --ignore-unknown
      - name: Setup database
        run: bundle exec rake db:setup
      - name: Precompile assets
        run: bundle exec rake assets:precompile
      - name: List precompiled assets
        run: ls -R public/assets
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID || 'be5d5c80290cec6da512f499e486898d5cc955994121458e7cec55455fbef7b5' }}
        with:
          coverageCommand: bundle exec rake
